name: PR from upstream

on:
  push:
    branches:
      - '**-from-stash'

jobs:
  create_pr:
    name: Create PR from upstream

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout upstream
        uses: actions/checkout@v2
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "${{ github.events.push.ref }}"
          base: master
          title: Update from internal repo
          body: Automated update of shared part
          # token: ${{ secrets.SEC_TOKEN }}
