name: PR from upstream

on:
  push:
    branches:
      - '**-from-stash'

jobs:
  create_pr:
    name: Create PR from upstream

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout upstream
        uses: actions/checkout@v2
      - name: Create PR
        id: pr_create
        run: gh pr create --base master --body "Automated update of shared part" --title "Update from internal repo"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Handle non-deadly error
        if: steps.pr_create.status != 'success'
        run: |
          set -x
          exit_code=$?
          if [ $exit_code -gt 1 ]; then exit $exit_code; fi
