name: 'to bb'

on:
  push:
    branches:
      - master

jobs:
  filter_diff:
    name: Filter out exclusive part

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Delete old branch
        run: ls && git log --oneline -n10 && git diff ${{ github.event.before }} -- . :^exclusive
