name: 'to bb'

on:
  push:
    branches:
      - master

jobs:
  filter_diff:
    name: Filter out exclusive part

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get diff
        run: git diff ${{ github.event.before }} -- . :^exclusive
