name: 'to bb'

on:
  push:
    branches:
      - master

jobs:
  filter_diff:
    name: Filter out exclusive part

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Get diff
        id: diff
        run: |
          DIFF_CONTENT=$( git diff --patch ${{ github.event.before }} )
          DIFF_CONTENT="${DIFF_CONTENT//'%'/'%25'}"
          DIFF_CONTENT="${DIFF_CONTENT//'$'/'%24'}"
          DIFF_CONTENT="${DIFF_CONTENT//$'\n'/'%0A'}"
          DIFF_CONTENT="${DIFF_CONTENT//$'\r'/'%0D'}"
          echo "::set-output name=content::$DIFF_CONTENT"
      - name: Show diff
        run: echo "${{ steps.diff.outputs.content }}"
      - name: Checkout BB upstream
        uses: actions/checkout@v2
        with:
          ref: bb-upstream
          persist-credentials: false
      - name: Commit shared changes
        if: steps.diff.outputs.content != ''
        run: |
          git config --local user.email "zudin.0197@gmail.com"
          git config --local user.name "BB upstream action"
          echo "${{ steps.diff.outputs.content }}" | git apply
          git commit -m "Update BB upstream" -a
      - name: Push to BB upstream
        if: steps.diff.outputs.content != ''
        uses: ad-m/github-push-action@master
        with:
          branch: bb-upstream
